name: Makefile CI

on:
  push 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make install

    - name: Run check
      run: make test

    - name: Run test
      run: make lint
